name: agendaservices
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0938342995941639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6171666269656271
  lightness: 0.33569488930515945
  saturation: 0.8125
  rhythmicContrast: 0.05400442820973694
purpose: []
