analytics: {}
color:
  brandColors:
    - '#C0C0A8'
    - '#000000'
    - '#888878'
    - '#000000'
    - '#000000'
  brandStrength: 0.617166
  lightness: 0.335694
  rhythmicContrast: 0.609234
  saturation: 0.8125
cta: {}
layout_spectrum: 0.231981
name: agendaservices
opengraph: {}
purpose: []
typography_spectrum: 0.093834
